[package]
name = "androidfs_driver"
version = "0.1.0"

[dependencies]
bincode = "1.3.3"
byteorder = "1.4.3"
linked-hash-map = "0.5.4"
serde = { version = "1.0.136", features = ["derive"] }
log = "0.4.16"
env_logger = "0.9.0"
rand = "0.8.5"
sysinfo = "0.23.5"
widestring = "0.4.3"

[target.'cfg(windows)'.dependencies]
winapi = "0.3.9"
dokan = "0.2.0+dokan150"

[[bin]]
name = "androidfs_driver"
path = "src/driver.rs"


[[bin]]
name = "androidfs_server"
path = "src/server.rs"
