[package]
name = "androidfs_server"
version = "0.1.0"

[dependencies]
androidfs_shared = { path = "../shared" }
bincode = "1.3.3"
byteorder = "1.4.3"
serde = { version = "1.0.136", features = ["derive"] }
rand = "0.8.5"
sysinfo = "0.23.5"