[package]
name = "androidfs_driver"
version = "0.1.0"

[dependencies]
dokan = "0.2.0+dokan150"
widestring = "0.4.3"
winapi = "0.3.9"
androidfs_shared = { path = "../shared" }
bincode = "1.3.3"
byteorder = "1.4.3"
linked-hash-map = "0.5.4"
serde = { version = "1.0.136", features = ["derive"] }
log = "0.4.16"
env_logger = "0.9.0"