name: Cargo Build

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build project
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup update nightly && rustup default nightly
      - run: cargo install cargo-ndk
      - run: rustup target add aarch64-linux-android
      - run: ./build.ps1
      - name: Artifact Upload
        uses: actions/upload-artifact@v2
        with:
          name: AndroidFS.exe
          path: ./target/release/*.exe
